version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: schedule-app-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-api:
      build: ./backend
      container_name: schedule-app-backend
      restart: always
      ports:
        - "8080:8080"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${DB_NAME}
        - SPRING_DATASOURCE_USERNAME=${DB_USER}
        - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    

volumes:
  postgres_data: